name: Deploy to AWS Lambda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-2
  FUNCTION_NAME: TodoLambdaFunction

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install Lambda Tools
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          dotnet tool update -g Amazon.Lambda.Tools

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Deploy Lambda
        working-directory: ./TodoLambda/src/TodoLambda
        run: |
          dotnet lambda deploy-function ${{ env.FUNCTION_NAME }} \
            --function-role ${{ secrets.LAMBDA_ROLE_ARN }} \
            --function-publish true

      - name: Update Function Configuration
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ env.FUNCTION_NAME }} \
            --environment Variables={ENVIRONMENT=production}
